---

# Deploy certificate configuration data 
- name: Deply certificate generation configuration files
  copy: 
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
   - { src: "{{ role_path }}/files/ca-config.json",
       dest: "{{ ca_config_file }}"}
   # CSR files
   # TODO replace csr files with j2 templates
   - src: "{{ role_path }}/files/ca-csr.json"
     dest: "{{ ca_csr_config_file }}"
   - src: "{{ role_path }}/files/kubernetes-csr.json"
     dest: "{{ k8s_csr_config_file }}"
   - src: "{{ role_path }}/files/admin-csr.json"
     dest: "{{ admin_csr_config_file }}"
   - src: "{{ role_path }}/files/kube-proxy-csr.json"
     dest: "{{ kube_proxy_csr_config_file }}"
   - src: "{{ role_path }}/files/kube-controller-manager-csr.json"
     dest: "{{ kube_controller_manager_csr_config_file }}"
   - src: "{{ role_path }}/files/kube-scheduler-csr.json"
     dest: "{{ kube_scheduler_csr_config_file }}"
   - src: "{{ role_path }}/files/kube-service-account-csr.json"
     dest: "{{ kube_service_account_csr_config_file }}"
   - src: "{{ role_path }}/files/kube-registry-web-csr.json"
     dest: "{{ kube_registry_web_csr_config_file }}"

# TODO make all csr generation be from a template
- name: Generate the certificate config file for nodes (file same on all nodes)
  template:
    src: "{{ role_path }}/templates/node-csr.json.j2" 
    dest: "{{ csr_dir }}/{{ item }}-csr.json"
  loop: "{{ groups['nodes'] }}"
       
- name: Generate a self-signed CA cert and private key for the k8s cloud
  shell: "cfssl gencert -initca {{ ca_csr_config_file }} | cfssljson -bare ca"
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ ca_pem_file }}" # also ca-key.pem, ca.csr

- name: Create crt version of the ca.pem cert file
  shell: "openssl x509 -in {{ ca_pem_file }} -inform PEM -out {{ ca_crt_file }}"
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ ca_crt_file }}"

- name: Generate Certificate and private key for k8s API server
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -hostname={{ apiserver_cluster_ip }},{{ master_ips_csv }},127.0.0.1,kubernetes.default \
         -profile=kubernetes \
         {{ k8s_csr_config_file }} | cfssljson -bare kubernetes
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ k8s_pem_file }}" # also kubernetes.csr kubernetes-key.pem

- name: Generate admin certificates 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ admin_csr_config_file }} | cfssljson -bare admin 
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ admin_pem_file }}" # also admin.csr admin-key.pem

- name: Generate kube-proxy client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_proxy_csr_config_file }} | cfssljson -bare kube-proxy
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_proxy_pem_file }}" # also kube-proxy.csr kube-proxy-key.pem

- name: Generate kube-controller-manager client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_controller_manager_csr_config_file }} | cfssljson -bare kube-controller-manager
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_controller_manager_pem_file }}" # also kube-controller-manager.csr kube-controller-manager-key.pem

- name: Generate kube-scheduler client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_scheduler_csr_config_file }} | cfssljson -bare kube-scheduler
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_scheduler_pem_file }}" # also kube-scheduler.csr kube-scheduler-key.pem

- name: Generate service-account client cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_service_account_csr_config_file }} | cfssljson -bare service-account
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_service_account_pem_file }}" # also kube-service-account.csr kube-service-account-key.pem

- name: Generate registry web cert and private key 
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -profile=kubernetes \
         {{ kube_registry_web_csr_config_file }} | cfssljson -bare registry-web
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ kube_registry_web_pem_file }}" # also .csr .pem

- name: Generate the specific certificate and Private key for each node when it does not already exist
  shell: cfssl gencert \
         -ca={{ ca_pem_file }} \
         -ca-key={{ ca_key_file }} \
         -config={{ ca_config_file }} \
         -hostname={{ hostvars[item].inventory_hostname }},{{ hostvars[item].ansible_host }} \
         -profile=kubernetes {{ csr_dir }}/{{ hostvars[item].inventory_hostname }}-csr.json | cfssljson -bare {{ hostvars[item].inventory_hostname }}
  args:
    chdir: "{{ cert_dir }}"
    creates: "{{ cert_dir }}/{{ item }}.pem"
  loop: "{{ groups['nodes'] }}"


- name: Discover if encryption config has already been generated
  stat: 
    path: "{{ encryption_config_file }}"
  register: ecf

- name: Generate an encryption key 
  shell: head -c 32 /dev/urandom | base64
  args:
    creates: "{{ encryption_config_file }}"
  register: encryption_key # used in template file
  when: ecf.stat.exists == False

- name: Generate the encryption config file
  template: 
    src: "{{ role_path }}/templates/encryption-config.yaml.j2"
    dest: "{{ encryption_config_file }}"
  when: ecf.stat.exists == False


